CREATE TABLE CUSTOMER (
	ID INT PRIMARY KEY,
	NO VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL
);
CREATE TABLE SERVICE_REQUEST (
	PRODUCT_NO VARCHAR(100) PRIMARY KEY,
	CUSTOMER_ID INT NOT NULL,
    DESCRIPTION VARCHAR(100)
);